// ReSharper disable UnusedAutoPropertyAccessor.Global
namespace Sefer.Backend.Api.Models.Public.Users;

/// <summary>
/// Activation of a user account
/// </summary>
public class ActivationPostModel
{
    /// <summary>
    /// Random stuff acting as a second salt
    /// </summary>
    public string Random { get; set; }

    /// <summary>
    /// The id of the user to activate
    /// </summary>
    public int User { get; set; }

    /// <summary>
    /// The hash to prove the url is generated by the back-end
    /// </summary>
    public string Hash { get; set; }
}
