// ReSharper disable UnusedAutoPropertyAccessor.Global
namespace Sefer.Backend.Api.Models.Public.Users;

/// <summary>
/// Model for resetting passwords
/// </summary>
public class PasswordResetPostModel
{
    /// <summary>
    /// Random stuff acting as a second salt
    /// </summary>
    public string Random { get; set; }

    /// <summary>
    /// The date the url was generated
    /// </summary>
    public string Date { get; set; }

    /// <summary>
    /// The id of the user to reset
    /// </summary>
    public int User { get; set; }

    /// <summary>
    /// The hash to prove the url is generated by the back-end
    /// </summary>
    public string Hash { get; set; }

    /// <summary>
    /// The new password of the user
    /// </summary>
    [Required]
    [MinLength(8)]
    public string Password { get; set; }

    /// <summary>
    /// The language code of the mail to send to the user
    /// </summary>
    public string Language { get; set; }
}
