// ReSharper disable UnusedAutoPropertyAccessor.Global
namespace Sefer.Backend.Api.Models.Public.Users;

/// <summary>
/// This model defines all the required input do deal with changing an email-address
/// </summary>
/// <inheritdoc />
public class UpdateEmailPostModel : ITimeProtectedModel
{
    /// <summary>
    /// This method contains the Data with encrypted information to deal with the change of the email
    /// </summary>
    public string EncryptedData { get; set; }

    /// <summary>
    /// Random stuff acting as a second salt
    /// </summary>
    /// <inheritdoc />
    public string Random { get; set; }

    /// <summary>
    /// The date the url was generated
    /// </summary>
    /// <inheritdoc />
    public string Date { get; set; }

    /// <summary>
    /// The hash to prove the url is generated by the back-end
    /// </summary>
    /// <inheritdoc />
    public string Hash { get; set; }

    /// <summary>
    /// The new password of the user
    /// </summary>
    [Required]
    [MinLength(8)]
    public string Password { get; set; }

    /// <summary>
    /// The language of the mail to send to the user
    /// </summary>
    public string Language { get; set; }

    /// <summary>
    /// Gets or sets the new email of the user, must be a full qualified email-address
    /// </summary>
    [EmailAddress]
    [Required]
    public string New { get; set; }

    /// <summary>
    /// Gets or sets (current) email of the user, must be a full qualified e-mail address
    /// </summary>
    [EmailAddress]
    [Required]
    public string Email { get; set; }

    /// <summary>
    /// Gets or sets old email of the user, must be a full qualified e-mail address
    /// </summary>
    public string Old => Email;

    /// <summary>
    /// Implementation of the interface.
    /// Data is 'named' to encryptedData to prevent confusion in the front-end
    /// </summary>
    public string Data => EncryptedData;
}

