global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using Sefer.Backend.Api.Data.Models.Abstractions;
global using Sefer.Backend.Api.Data.Models.Constants;
global using Sefer.Backend.Api.Data.Models.Courses;
global using Sefer.Backend.Api.Data.Models.Courses.Curricula;
global using Sefer.Backend.Api.Data.Models.Courses.Lessons;
global using Sefer.Backend.Api.Data.Models.Courses.Rewards;
global using Sefer.Backend.Api.Data.Models.Enrollments;
global using Sefer.Backend.Api.Data.Models.Financials;
global using Sefer.Backend.Api.Data.Models.Logging;
global using Sefer.Backend.Api.Data.Models.Resources;
global using Sefer.Backend.Api.Data.Models.Users;
global using Sefer.Backend.Api.Data.Models.Users.Chat;
global using Sefer.Backend.Api.Data.Requests.Entities;
global using Sefer.Backend.Support.Lib.Mediator;
global using Sefer.Backend.SharedConfig.Lib.Abstractions;
global using Survey = Sefer.Backend.Api.Data.Models.Courses.Surveys.Survey;
global using WebsiteSettings = Sefer.Backend.Api.Data.Models.Settings.Settings;